# Generated by Django 3.2 on 2022-08-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('paddress', models.CharField(blank=True, max_length=200, null=True)),
                ('tempaddr', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('social_media', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('skills', models.TextField(blank=True, max_length=500, null=True)),
                ('experience', models.TextField(blank=True, max_length=500, null=True)),
                ('awards', models.TextField(blank=True, max_length=500, null=True)),
                ('interest', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
